Milestone 3: Feature/events
chrystalme/magic-books-inc pull request #5
Opened 2021-08-02 15:23 UTC by SarvarKh

# Magic Books Inc - Milestone 3: Feature/events
**In this milestone, we have:**
- [x] made the BooksForm component stateful;
- [x] connected BoosForm with redux store;
- [x] implemented ADD_BOOK and REMOVE_BOOK to the components;
- [x] fixed linter errors;

2021-08-02 16:28 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check my comments under this review;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best**

2021-08-02 16:28 UTC, bellom commented on src/components/Book.jsx
> +import { connect } from 'react-redux';
Opps 🤦 , let's stick to best practice and project guidelines.

Let's remove this line, we don't need it so far we are passing the method down to the Book component as a prop.

In milestone 2, you were introduced to the `component` and `container` folders.

And it was stated that the `book.jsx` would be a presentational component.

Note:  Presentational components for stateless components and a container/page folder for other components that use the state/redux-store.

More Explanation: 
React bindings for Redux separate presentational components from container components. This approach can make your app easier to understand and allow you to more easily reuse components. In your components directory (presentational components) you have components that are not connected to the Redux store, and on your containers directory, you have components that are connected to the Redux store. Read More... https://www.pluralsight.com/guides/how-to-structure-redux-components-and-containers

2021-08-02 16:28 UTC, bellom commented on src/containers/BooksForm.js
> +    <form>
For the booksForm handleSubmit function, It has to be attached to the form's onSubmit event. This way you can add validation to the input fields by adding the required attribute, and write less code as it is also one of the best practices.
 
 Screenshot from pathwright:
 
![image](https://user-images.githubusercontent.com/31897434/127893627-9b03d3b3-5839-4288-be5c-2f6a42eb11a2.png)

2021-08-03 06:47 UTC, chrystalme commented
### Update
- [x]  Remove connect from book to make it presentation only component
- [x] Handle-Submit from form's event 

Thanks for taking the time to review our project 😃

2021-08-03 10:52 UTC, oloomoses approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Slack: Oloo Moses_

2021-08-03 13:20 UTC, merged